### PR TITLE
Travis-CI support added 

### PR DESCRIPTION
**Pull request by wardbekker**
Hi Jesper,

Here the config file needed for building on http://travis-ci.org. See http://about.travis-ci.org/docs/user/getting-started/ on how you can Sign In with OAuth on travis-ci.org, and add service hooks to your project. Let me know if I can help you.

Tnx!

Ward

### CODE REVIEW

**Comment by jlouis** [comment]
This looks rather nice. Going in.

**Comment by ghost** [comment]
Hi!

We used to kind of run a Hudson instance that we lost when i quite my job. On that instance we compiled and ran tests on R13B04, R14A and R14B03. The latter being the latest and greatest. The former are what you find in the package repositories of GNU/Linux distributions that fail on Erlang.

As jlouis said, travis-ci looks rather nice. It would definently benefit from supporting these older Erlang releases, the difference between them are larger than what you find between the R14B-releases and therefore they generate more issues for new users who run into problems with packages not being tested against them.

**Comment by wardbekker** [comment]
Hi klaar, we'll provide older Erlang/OTP releases in the near future on travis. 

Jesper, don't forget to Sign In with OAuth on travis-ci.org, and add service hooks to your project as described here: http://about.travis-ci.org/docs/user/getting-started/. Otherwise etorrent won't show up on Travis-ci.org

**Comment by jlouis** [comment]
Just signed in. :)

**Comment by ghost** [comment]
@wardbekker Good to hear. It's one of those issues that pop up too often.

**Pull request merged**
