### PR TITLE
Refactor etorrent_peer_recv to minimize state passing

### PR DESCRIPTION
**Pull request by edwardw**
Hi,

I've refactor-ed module etorrent_peer_recv to eliminate unnecessary state passing between functions. `make eunit` and `make dialyze` are all good. And in one test run, it also successfully started to downloading one torrent file.

Please review my change.

Regards,
Edward

### CODE REVIEW

**Comment by jlouis** [comment]
See the comment on L148. It generates some warnings, but is harmless for the code apparently due to the survivability of Erlang :)

**Comment by edwardw** [comment]
I also tried to refactor etorrent_peer_control a little bit. Please take a look. In the meantime, I will move on to other issues / enhancements.

**Comment by jlouis** [comment]
Cool, taking a look later today

**Comment by jlouis** [comment]
Also pulled to `next`. I plan a move to `master` later when it has been tested a bit.

**Pull request merged**
