### PR TITLE
Piece set rebase

### PR DESCRIPTION
**Pull request by ghost**
This branch should be ready to get merged back into master.

The download algorithm has been updated and some additional modules has been added to support it.

Comments and suggestions are welcome. :)

### CODE REVIEW

**Comment by jlouis** [comment]
Awesome, will get a pull/test on later today when I've written slides for a talk Saturday :)

**Comment by jlouis** [comment]
If I naively pull it into master, there is a simple conflict in `etorrent_utils` which I can fix myself, but loading a ubuntu torrent into it make my client explode:

```
    =CRASH REPORT==== 3-Mar-2011::17:00:17 ===
  crasher:
    initial call: etorrent_fast_resume:init/1
    pid: <0.90.0>
    registered_name: []
    exception exit: {{badmatch,{error,{not_a_dets_file,"/home/jlouis/etorrent/priv/fast_resume.tab"}}},  [{etorrent_fast_resume,init,1},{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}
      in function  gen_server:init_it/6
      in call from proc_lib:init_p_do_apply/3
    ancestors: [etorrent_sup,<0.81.0>]
    messages: []
    links: [<0.83.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 377
    stack_size: 24
    reductions: 181
  neighbours:
```

So I go kill the DETS file (even though it has been created as a DETS file (I think, will have to check it). Then the following error occurs:

```
=CRASH REPORT==== 3-Mar-2011::17:03:51 ===
  crasher:
    initial call: supervisor:etorrent_io_sup/1
    pid: <0.139.0>
    registered_name: []
    exception exit: {{badmatch,"/home/jlouis/etorrent"},[{etorrent_io_sup,init,1},{supervisor,init,1},{gen_server,init_it,6},{proc_lib,init_p_do_apply,3}]}
      in function  gen_server:init_it/6
      in call from proc_lib:init_p_do_apply/3
    ancestors: [<0.114.0>,etorrent_torrent_pool,etorrent_sup,<0.81.0>]
    messages: []
    links: [<0.114.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 24
    reductions: 248
  neighbours:
```

Which seem to be a bug in the init code of the supervisor. I expect it to be the config file which returns something wrong. Do you want to fix, or should I get cracking on the code?

**Comment by ghost** [comment]
It's probably due to changes in etorrent_config, it return either {dir, DirPath} or DirPath depending upon the local settings.

**Comment by jlouis** [comment]
Confirmed :)

**Comment by ghost** [comment]
Good to know. I can fix the explicit match on {dir, _} in etorrent_io_sup and ensure that the config alues are never tagged with the key.

**Comment by ghost** [comment]
The cause of the problem was that values were inconsistently returned as tagged or untagged from the functions that read the configuration. That last commit solves that problem.

**Comment by ghost** [comment]
The last commit ensures that those upgrading from previous etorrent versions don't need to decipher that error message you got.

**Comment by jlouis** [comment]
# Alterations:

## Etorrent Peer Control:
- etorrent_peer_control:handle_endgame_got_chunk:
  I'd like to discuss if we should push State "down" from the
  top-level stuff. Especially because I want to limit the passing
  around of the state if possible. Yes, it passes fewer parameters,
  but it also ends up permeating everything with "State" which I don't
  particularly like. You may have another viewpoint though.
  
  statechange_interested too.
- Q: Why does the chunk manager return the peers to tell about the chunk we
  just got?
- Q: What is the return type of chunk_mgr:mark_fetched/4
- Q: chunk_mgr:request_chunks/4 - I don't like using `{error,
  not_interested}` since it is hardly an error.

# New files:

## create mode 100644 apps/etorrent/src/etorrent_chunkset.erl

Looks really nice.

## create mode 100644 apps/etorrent/src/etorrent_monitorset.erl

Monitor is a great idea we should use in other places of the client I
think. It is quite a nice generalization of what is happening in
multiple places, so use the code to describe the intention, even if it
as simple as the monitor-set-code.

## create mode 100644 apps/etorrent/src/etorrent_pieceset.erl

Awesome code. That ought to help a _lot_ on the internals. Updates in
them are quite expensive though, but the question is if it is
measurable at all in the heat of things. I am willing to bet it is not
enough to worry about for now. By the way, this code looks better than
my haskell in many ways.

I like min_ is bin-searching :)

## Chunk_mgr code needs a reread as well (!)

The only thing I am somewhat worried about is that the piece manager
is used by many other systems and I can't really see if it is
maintained correctly, but that is what tests are for :)

**Comment by ghost** [comment]
## regarding handle_endgame

We are on the same page, we should pass each value that a function needs from the state as a separate parameter. It should return the new versions of those values as a tuple, if that is the intention of the function.

## regarding returning peers

My original intention was to return the list of peers that also have an outstanding request for the same chunk and make the
peer that first received the chunk responsible for telling the others so that they can cancel their requests.

A better way to solve this problem is to make the peers, or another process, responsible for mapping
outstanding requests to peers. chunk_mgr would return true if this was the first time that the chunk has
been marked as fetched. We don't want to end up with god processes.

## regarding {error, not_interested}

true, this could as well be {ok, not_interested}.

## regarding piece manager

I agree, we need tests for that.

**Comment by ghost** [comment]
## fixes for peerlist and not interested

I've updated the etorrent_chunk_mgr and etorrent_peer_control modules to use the new return types. The tests are also updated.

https://github.com/klaar/etorrent/tree/pieceset-typefixes

**Pull request merged**
