### PR TITLE
UPnP support

### PR DESCRIPTION
**Pull request by edwardw**
Hi,

My patch of UPnP support for etorrent is ready to be reviewed. This takes much longer than I may have expected. Turns out imperative and share state way of thinking is so stubborn on me.

Please note that:
- Seems there are some release stuff needs to be taken care of. `make && make eunit` works, but etorrent crashes. The idea is to get code out as soon as possible. So you can review the code. Hope it is not too ugly :P
- It depends on my fork of ibrowse for now. After official ibrowse repo accepts my patch, the dependence will be changed.

Regards,
Edward

### CODE REVIEW

**Comment by jlouis** [comment]
I've gone through the new files and they also look awesome. I'd rather pull it in so we can work directly on it. There are some minor stylistic things, but I don't think it warrants going over before pulling it in. In any case, I did not find anything from a first skim that looks like it needs immediate attention.

**Comment by jlouis** [comment]
Another round of suggestions. I have a ZyXel P-660R-D1 router here capable of upnp as well, so I'll give it a spin. It is up to you if I should pull it as is or you want a round of cleanups first.

Also, I've looked over the design from a more top-level view. It looks quite sound and I would probably have implemented likewise.

**Comment by edwardw** [comment]
Etorrent can be launched with upnp support on now. Please take it for a spin. UPnP subsystem desperately needs to be tested against more routers.

**Comment by edwardw** [comment]
All comments except klaar's try-catch one and jlouis' ets table one are addressed. Those two are a little more complicated than others.

Thanks for your comments, guys!

**Comment by edwardw** [comment]
And yes, please pull it.

**Comment by jlouis** [comment]
Will do!

**Comment by jlouis** [comment]
Pulled to `next` for some test runs. Going to `master` this weekend if no problems show up.

**Comment by jlouis** [comment]
Took it for a spin. It works quite well, but my test framework has a slight problem: I run two etorrent clients at the same time (seeder and leecher) and then of course, I get eaddrinuse errors when I try to start the second one. Is it enough to simply add a port knob in the configuration file, or do you also have to tell the networking part of the upnp subsystem that the port is not 8888?

**Comment by edwardw** [comment]
Ah, it is mochiweb http server. Fixed and added a unit test for that.

**Comment by edwardw** [comment]
Addressed two remaining comments:
- klaar's one about try-catch. I feel I have good reason to keep it as is. Please see my inline comment for reasoning.
- jlouis' ets table one. It has be done. UPnP ETS table is owned by `etorrent_table` now. It also monitors upnp entity pid to do housekeeping if necessary.

**Comment by jlouis** [comment]
Neat, will be pulling to 'next' :)

**Comment by jlouis** [comment]
All tests are good! If nothing shows up, this goes to 'master' soon.

**Comment by edwardw** [comment]
Sounds good! Thanks for taking care of this.

**Comment by jlouis** [comment]
Pushed to master. A bit late, but I decided to run some tests on it. Thanks for providing the code!

**Pull request merged**
