### PR TITLE
Bug68 patch

### PR DESCRIPTION
**Pull request by edwardw**
Hi Jesper,

I'd like you to review my fix for bug 68, i.e. Trying to load a .png as a .torrent file crashes etorrent.

Regards,
Edward

### CODE REVIEW

**Comment by jlouis** [comment]
Neat, I'll probably get around to it later today :)

**Comment by jlouis** [comment]
It looks good. I'll cherry-pick it to `next` for some cooking unless you want to hack more on it.

**Comment by edwardw** [comment]
I added event notification code as you suggested. And merged with upstream changes. If all looks good, please go ahead and integrate this patch.

**Comment by edwardw** [comment]
By the way, you mentioned `next` branch. Do you recommend to fork and work on that branch instead of master branch?

**Comment by edwardw** [comment]
Forgot to run unit tests before. Turns out my patch will fail some of them. Fixed.

**Comment by jlouis** [comment]
Perhaps I should plug `documentation/git.md` some more in the README file. But the shorter answer is that it is usually better to base changes off `master` - unless you really need something that is only present in `next`. I often make a branch `test` locally and then pull in the branch I am working on and `next` to test. That way, I get to easily test my changes against other changes present, but still have the independence of `next` present.

`master` tend to be much more tested for stability than `next` - which occasionally is riddled with regressions when we pull something high-impact to it. Base off `maint` if it a change to fix the production system in some way.

**Comment by jlouis** [comment]
Oh, and btw, pulled to `next` for some cooking :)

**Comment by jlouis** [comment]
The beast here seem to fail `next` since the `bcoding:decode/1` call present in `etorrent_tracker_communication` is not handled. The dialyzer actually seem to catch this:
- run `rebar build-plt` - and then go hack some Coq, Agda, drink a _large_ jug of coffee, buy groceries and treat the wife.
- `make dialyze` - we have some errors currently but the problems in tracker communication pertaining to the problem should stand out rather well. Culprit error is:
  
  ```
      etorrent_tracker_communication.erl:226: The call     etorrent_tracker_communication:handle_tracker_response({'error',_} | {'ok',binary() | [binary() | [any()] | integer() | {_,_}] | integer()},S::#state{url::[[[any()]]],info_hash::string(),peer_id::string(),torrent_id::integer()}) will never return since it differs in the 1st argument from the success typing arguments: ([any()],#state{soft_timer::'none' | reference(),hard_timer::'none' | reference(),url::[[[any()]]]})
  ```

**Comment by edwardw** [comment]
Holy shit, `rebar build-plt` is really a cpu hog. But it is very good to know erlang has a tool like dialyzer. Kudos to whoever wrote it.

And the error has been fixed.

**Comment by jlouis** [comment]
Pulled to next, thanks!

By the way, there is usually little reason to merge master to your branch, unless you need something from master that your code is dependent on. It is usually better to keep the branch point and then know that the point at which you branch was somewhat stable.

**Comment by edwardw** [comment]
I see. And looking forward to contributing more.

**Comment by jlouis** [comment]
I'll cook the patch for a little series of test runs. It looks fine currently, and then I'll push the guy to 'master' and get around to closing the issue (I'll probably create a new one for the Filename/Torrent pushback).

**Pull request closed without merging**
